### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by foxpcteam** [jesperbjerke/wa-fronted#10]
Hi,
when the editor will have full RTL Support?

**Comment by 13pixlar** [comment]
When the developer has the time to implement it. This software is free and open source so try and be a little nice...

**Comment by jesperbjerke** [comment]
Seems to be reasonably easy to add, a quick search pointed me to the dir="rtl" attribute, not sure if this is enough to make it truly rtl compatible but worth a try

**Comment by jesperbjerke** [comment]
Added in v0.6.1
