### ISSUE TITLE
PHP Notice: WordPress does not initiate PHP Sessions

### ISSUE THREAD

**Issue by rhurling** [jesperbjerke/wa-fronted#14]
In https://github.com/jesperbjerke/wa-fronted/blob/master/wa-fronted.php#L87 you save the Options in the PHP $_SESSION variable, which is by default not initialised through WordPress and will generate a PHP Notice.
I'm pretty sure you could just use a static variable in the WA_Fronted class and replace every reference to `$_SESSION['wa_fronted_options']` with `WA_Fronted::$options`.

**Comment by jesperbjerke** [comment]
Hm, I do however call session_start() before I use the session variable. I use a session variable to avoid unnecessary compiling of the options. But when I look at the code I realise it compiles on every page load anyways. I'll look into this, static variable might be just fine.

**Comment by jesperbjerke** [comment]
fixed in v1.1
