### ISSUE TITLE
'permission' field should allow booleans

### ISSUE THREAD

**Issue by r-a-y** [jesperbjerke/wa-fronted#17]
Hi Jesper,

Great plugin!  Just looking into WA Fronted.  I've found that the `'permission'` field is restricted only to roles.

What if we wanted to pass our own capability check such as `current_user_can( 'edit_XXX', $post_id )`?

If `'permission'` is a string like the current options (default, logged-in, misc. role), then the `check_permission()` method should continue parsing.  If a boolean is explicitly passed like in the above example, do not parse and trust the plugin.

**Comment by jesperbjerke** [comment]
Good suggestion! Will add it in next release :)
