### ISSUE TITLE
Why does the JS save() method use location.reload()?

### ISSUE THREAD

**Issue by r-a-y** [jesperbjerke/wa-fronted#18]
In other words, when hitting "Save", why does WA do a full page refresh?  The [FEE](https://github.com/iseulde/wp-front-end-editor) plugin does not do this.

Just wondering if there were any design decisions that went into this.

**Comment by jesperbjerke** [comment]
It was to avoid some unnecessary DOM manipulation and ensure everything is loaded properly. But it might be fine just removing it. Will require some testing though.

**Comment by jesperbjerke** [comment]
Seems to work straight off. Adding in next release.

**Comment by r-a-y** [comment]
Cool!  Perhaps the `location.reload()` code could be toggled if it was a [filter option](https://github.com/jesperbjerke/wa-fronted/wiki/Options) just in case some prefer the page refresh.

I have another question regarding saving that I'll open a new issue for.

**Comment by jesperbjerke** [comment]
Yeah, it's easily added if someone requests it. Right now i'll keep it simple and do it one way. :)
