### ISSUE TITLE
Ability to pass additional data during AJAX save?

### ISSUE THREAD

**Issue by r-a-y** [jesperbjerke/wa-fronted#20]
In the JS `save()` function, WA Fronted only passes `'content'` and `'options'` during AJAX:

```
						save_this.push({
							'content' : content,
							'options' : editors[i].options
						});
```

What if a plugin has other data they want to pass?  Currently, a plugin cannot pass extra data without adding it to TinyMCE's `'options' ` data.

Perhaps take a page out of the FEE plugin:
https://github.com/iseulde/wp-front-end-editor/blob/master/src/js/fee.js#L222-L237

Pass an existing object that already has data in it.

If the TinyMCE options method is the preferred way to go regarding metadata, then disregard this issue!

**Comment by jesperbjerke** [comment]
Definitely something to consider. Could you provide an example of data that should/could be passed outside of `options` ?

**Comment by jesperbjerke** [comment]
In version 1.3.6, additional data will be able to be passed through filters `autosave_extra_data` and `save_extra_data`, and will be accessible through the key `extra` in $data array on save/autosave actions
