### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by foxpcteam** [jesperbjerke/wa-fronted#22]
Hi,
i working with multisite. after i have install the wa-fronted in multisite network i was able to see the plugin and could activate the plugin by "network activate" for the all network.

but when i got to some site wp-admin i don't see the wa-fronted in the plugin list to activate the plugin site by site.

you can enable multisite support and see the problem.

**Comment by khromov** [comment]
@foxpcteam When you network activate a plugin, it disappears from the site-specific plugin list, so this is correct behaviour for any plugin. If you network activate wa-fronted, it **is** enabled on all sites. (If it doesn't work though, that's a different story.)

Themes on the other hand, you'll first have to enable in the network admin and then you can activate them on each site.

**Comment by foxpcteam** [comment]
Hi @khromov,
i know how the network works.
as i said, i did not activate the wa-fronted as "network activate" i just install the wa-fronted plugin from the network (otherwise you can't install the plugins)

then i just go to some of my site and try to enable the wa-fronted plugin from the plugin list but did not see the wa-fronted plugin in the list.

i am working with network more than 2 years and install more than 100+ plugins so i know how to work with the network and each site as stand alone.

but here there is some strange bug that i never see.

**Comment by khromov** [comment]
@foxpcteam Ah, I understand your question better now.

The reason you don't see the plugin on the individual sites is because it has the `Network: true` directive in the plugin header:
https://github.com/jesperbjerke/wa-fronted/blob/master/wa-fronted.php#L15

@jesperbjerke I don't see a reason why Fronted would need this, was there some thought behind it?

**Comment by jesperbjerke** [comment]
I must've misunderstood the purpose of `Network: true`. Will remove it
