### ISSUE TITLE
Repeater Fields

### ISSUE THREAD

**Issue by trajche** [jesperbjerke/wa-fronted#25]
Repeater fields (http://www.advancedcustomfields.com/resources/repeater/) are super useful and would be amazing to see them included in this plugin. Any plans on implementing this?

**Comment by jesperbjerke** [comment]
Repeater fields should work, but through the ACF form modal. Read more about it here:  https://github.com/jesperbjerke/wa-fronted/wiki/Supported-fields#acf-field-types
